linha = input() .split()
print(linha)
c1 = int(linha[0])
n1 = int(linha[1])
v1 = float(linha[2])
linha2 = input() .split()
print(linha2)
c2 = int(linha2[0])
n2 = int(linha2[1])
v2= float(linha2[2])
vt = n1 * v1 + n2 * v2
print(f'VALOR A PAGAR = R${vt:.2f}') 