linha = input() .split()
print(linha)
c1 = int(linha[0])
n1 = int(linha[1])
n1 = float(linha[2])
linha2 = input() .split()
print(linha2)
c2 = int(linha2[0])
n2 = int(linha2[1])
n2= float(linha2[2])
nt = n1 * n1 + n2 * n2
print(f'nALOR A PAGAR = R${nt:.2f}') 